;IP Configuration Tools、DirectShow Public configuration files for tools such as
;Version: 3.0.2406.9211

[General]
Language=0

[FilterList]
GalaxyView=false
GxDriverManager=false
GxUpgradeTool=false

[ToolMenu]
GxGigeIPConfig_CN=IP配置工具
GxGigeIPConfig_EN=GxGigeIPConfig
GxGigeIPConfig_UAC=true

NICConfigTool_CN=网卡配置工具
NICConfigTool_EN=NICConfigTool
NICConfigTool_UAC=true

GxLogViewer_CN=日志查看工具
GxLogViewer_EN=GxLogViewer
GxLogViewer_UAC=true